### ISSUE TITLE
Readme suggestion

### ISSUE THREAD

**Issue by sbennett1990** [ibara/qotdd#1]
Perhaps include information on how to make the daemon start at boot? At least on OpenBSD. 

A helpful piece of information I discovered is that if you are configuring `qotdd` in `/etc/rc.local` (a la FAQ 10.3) then you must put an "&" at the end of the command invocation, otherwise the boot process will hang. I thought others may benefit from this kind of information.

**Comment by ibara** [comment]
That was my fault. I forgot the call to daemon(). All the daemons are now fixed.
FWIW, writing an rc script would be better:
````
#!/bin/sh
#
# $OpenBSD$

daemon="/usr/local/sbin/qotdd"

. /etc/rc.d/rc.subr

rc_reload=NO

rc_stop() {
        pkill -USR1 -xf "${pexp}"
}

rc_cmd $1
````

**Comment by sbennett1990** [comment]
Thanks for the tip! I'll give that a try.
